### ISSUE TITLE
"This repository is empty."

### ISSUE THREAD

**Issue by saskra** [BioSpecNorway/IRmHiRegistration#1]
I came here via the link from your paper. Are you still planning to publish the source code?

**Comment by pisarik** [comment]
Dear @saskra,

Sorry for delays, I think Stas will put the code soon. The most difficult part is to clean up your thousands lines of code to release it in a wild open source:)

**Comment by take5v** [comment]
Dear @saskra!

Now you can have a look at the source code.

Best regards,
Stas
